export default () => ({
  port: parseInt(process.env.PORT || '3001', 10),
  nodeEnv: process.env.NODE_ENV || 'development',
  corsOrigin: process.env.CORS_ORIGIN || 'http://localhost:3000',

  redis: {
    url: process.env.REDIS_URL || 'redis://localhost:6379',
  },

  // --- Resource isolation -------------------------------------------------
  // The load-bearing setting in this whole design. API processes and worker
  // processes get SEPARATE Postgres pools, and the sum of every pool across
  // every running process must stay below the server's max_connections.
  // Workers being starved is survivable; signup/login being starved is not.
  database: {
    url: process.env.DATABASE_URL,
    // Per API process. 10 x 2 API processes = 20 connections.
    apiPoolSize: parseInt(process.env.DB_POOL_API || '10', 10),
    // Per worker process. Deliberately smaller: scheduled updates are allowed
    // to take longer, but must never exhaust the pool the API needs.
    workerPoolSize: parseInt(process.env.DB_POOL_WORKER || '5', 10),
    // Fail a query rather than queue behind a saturated pool forever.
    poolTimeoutSeconds: parseInt(process.env.DB_POOL_TIMEOUT_SECONDS || '10', 10),
  },

  // --- Scheduled daily updates -------------------------------------------
  scheduler: {
    // Slots the day is divided into. 1440 = one per minute.
    slotsPerDay: parseInt(process.env.SCHEDULER_SLOTS_PER_DAY || '1440', 10),
    // Set false on API-only processes so exactly one deployment runs the
    // dispatcher loop; the tick is also guarded by a unique row per slot.
    enabled: (process.env.SCHEDULER_ENABLED ?? 'true') === 'true',
    // How far back a recovery sweep looks for slots that were missed while the
    // process was down. 120 slots = 2 hours at one-minute slots.
    recoveryLookbackSlots: parseInt(process.env.SCHEDULER_RECOVERY_LOOKBACK || '120', 10),
    // Rows pulled per keyset page when dispatching a slot.
    dispatchPageSize: parseInt(process.env.SCHEDULER_PAGE_SIZE || '500', 10),
  },

  // --- Queue / workers ----------------------------------------------------
  queue: {
    // Jobs a single worker process handles at once.
    updateConcurrency: parseInt(process.env.QUEUE_UPDATE_CONCURRENCY || '20', 10),
    // Throughput ceiling, enforced by BullMQ across every worker sharing this
    // Redis. This is the knob to raise once you know the database is happy:
    // 30/s is the starting target, not a structural limit.
    rateLimitMax: parseInt(process.env.QUEUE_RATE_LIMIT_MAX || '30', 10),
    rateLimitDurationMs: parseInt(process.env.QUEUE_RATE_LIMIT_DURATION_MS || '1000', 10),
    // Retries before a job is parked in the dead-letter queue.
    maxAttempts: parseInt(process.env.QUEUE_MAX_ATTEMPTS || '5', 10),
    backoffBaseMs: parseInt(process.env.QUEUE_BACKOFF_BASE_MS || '5000', 10),
    // Background (non-critical) work generated by signup/login.
    backgroundConcurrency: parseInt(process.env.QUEUE_BACKGROUND_CONCURRENCY || '5', 10),
  },

  // --- Caching ------------------------------------------------------------
  cache: {
    // Current content is small and read by every worker; a long TTL keeps
    // Postgres out of the per-update hot path entirely.
    contentTtlSeconds: parseInt(process.env.CACHE_CONTENT_TTL_SECONDS || '300', 10),
    enabled: (process.env.CACHE_ENABLED ?? 'true') === 'true',
  },

  jwt: {
    accessSecret: process.env.JWT_ACCESS_SECRET,
    accessTtl: process.env.JWT_ACCESS_TTL || '15m',
    refreshSecret: process.env.JWT_REFRESH_SECRET,
    refreshTtlDays: parseInt(process.env.JWT_REFRESH_TTL_DAYS || '30', 10),
  },

  cookies: {
    secure: (process.env.COOKIE_SECURE ?? 'true') === 'true',
    domain: process.env.COOKIE_DOMAIN || undefined,
  },

  argon2: {
    // Tuned for a small VPS (KVM 2, 8GB RAM). Raise memoryCost if you move to
    // a larger plan; keep an eye on request latency and RAM headroom under load.
    memoryCost: parseInt(process.env.ARGON2_MEMORY_COST || '19456', 10), // ~19 MB
    timeCost: parseInt(process.env.ARGON2_TIME_COST || '2', 10),
    parallelism: parseInt(process.env.ARGON2_PARALLELISM || '1', 10),
  },

  rateLimit: {
    ttlSeconds: parseInt(process.env.RATE_LIMIT_TTL_SECONDS || '60', 10),
    limit: parseInt(process.env.RATE_LIMIT_MAX || '20', 10),
  },

  captcha: {
    turnstileSecret: process.env.TURNSTILE_SECRET_KEY,
  },

  identityProvider: {
    apiKey: process.env.IDENTITY_PROVIDER_API_KEY,
    webhookSecret: process.env.IDENTITY_PROVIDER_WEBHOOK_SECRET,
  },

  identity: {
    // Keys the Aadhaar HMAC. Must be set, must never be committed, and must
    // never be rotated casually — changing it invalidates every stored hash
    // and so breaks duplicate detection for all existing users.
    aadhaarHashPepper: process.env.AADHAAR_HASH_PEPPER,
  },

  telegram: {
    botToken: process.env.TELEGRAM_BOT_TOKEN,
    // Used to build the t.me deep link the app shows. Without it the link is
    // unusable, so the Telegram endpoints refuse to serve one rather than
    // handing out a broken URL.
    botUsername: process.env.TELEGRAM_BOT_USERNAME,
    webhookSecret: process.env.TELEGRAM_WEBHOOK_SECRET,

    // The two chats every candidate must be in before verification completes.
    // Numeric Telegram chat IDs, negative for groups/channels.
    //  - public: normal join, membership shows up as `member` straight away.
    //  - private: invite-link-with-approval, so a pending join REQUEST is
    //    accepted as satisfying this step (a human admin approves later).
    publicChatId: process.env.TELEGRAM_PUBLIC_CHAT_ID
      ? BigInt(process.env.TELEGRAM_PUBLIC_CHAT_ID)
      : undefined,
    privateChatId: process.env.TELEGRAM_PRIVATE_CHAT_ID
      ? BigInt(process.env.TELEGRAM_PRIVATE_CHAT_ID)
      : undefined,
    publicChatInviteLink: process.env.TELEGRAM_PUBLIC_CHAT_INVITE_LINK,
    privateChatInviteLink: process.env.TELEGRAM_PRIVATE_CHAT_INVITE_LINK,

    // Separate from the two above: the group for candidates who have finished
    // BOTH counters and been selected. Served only to qualified users.
    selectedGroupInviteLink: process.env.TELEGRAM_SELECTED_GROUP_INVITE_LINK,
  },
});
