"""Generate the Future Fashion launcher icons from one set of shapes.

Writes the adaptive icon (vector foreground, background and monochrome
layers for Android 8+), PNG fallbacks for Android 7, and the 512 px
Play Store icon. Run it again after changing the shapes or colours:

    python3 -m pip install pillow
    python3 tool/make_icons.py        # from the mobile/ directory
"""

from __future__ import annotations

import math
from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
RES = ROOT / "android" / "app" / "src" / "main" / "res"

# Brand colours (lib/app/theme/colors.dart).
INK = (0x0B, 0x0A, 0x14)
GLOW = (0x2B, 0x21, 0x56)
GOLD_BRIGHT = (0xF6, 0xDD, 0xA8)
GOLD = (0xE8, 0xC0, 0x7A)
GOLD_DEEP = (0xB8, 0x89, 0x3F)

# Shapes on the 108 x 108 adaptive-icon canvas. Launchers show the middle
# 72 x 72 and may mask it to a circle, so everything stays inside the
# central 66-unit circle. An "ff" ligature: two stems under one top bar.
RECTS = [
    (32, 32, 76, 38),  # shared top bar
    (32, 32, 38, 76),  # first stem
    (32, 51, 48, 57),  # first middle bar
    (53, 32, 59, 76),  # second stem
    (53, 51, 70, 57),  # second middle bar
]
SPARKLE_CENTER = (69.5, 68.5)
SPARKLE_OUTER = 7.0
SPARKLE_INNER = 1.9

GRADIENT_START = (32, 32)
GRADIENT_END = (76, 76)
GRADIENT_STOPS = [(0.0, GOLD_BRIGHT), (0.55, GOLD), (1.0, GOLD_DEEP)]
GLOW_CENTER = (54, 36)
GLOW_RADIUS = 76

VISIBLE = (18, 90)  # the part of the canvas a launcher shows
LEGACY_SIZES = {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}
SUPERSAMPLE = 8


def sparkle_points() -> list[tuple[float, float]]:
    cx, cy = SPARKLE_CENTER
    points = []
    for i in range(8):
        angle = -math.pi / 2 + i * math.pi / 4
        radius = SPARKLE_OUTER if i % 2 == 0 else SPARKLE_INNER
        points.append((cx + radius * math.cos(angle), cy + radius * math.sin(angle)))
    return points


def hex_color(rgb: tuple[int, int, int]) -> str:
    return "#FF%02X%02X%02X" % rgb


def fmt(value: float) -> str:
    return f"{value:.2f}".rstrip("0").rstrip(".")


def mark_path() -> str:
    parts = [f"M{l},{t}H{r}V{b}H{l}Z" for l, t, r, b in RECTS]
    points = sparkle_points()
    parts.append("M" + "L".join(f"{fmt(x)},{fmt(y)}" for x, y in points) + "Z")
    return "".join(parts)


VECTOR_HEADER = (
    '<?xml version="1.0" encoding="utf-8"?>\n'
    "<!-- Generated by tool/make_icons.py. Edit the script, not this file. -->\n"
)


def write_vectors() -> None:
    stops = "\n".join(
        f'                    <item android:offset="{offset}" android:color="{hex_color(color)}" />'
        for offset, color in GRADIENT_STOPS
    )
    foreground = f"""{VECTOR_HEADER}<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path android:pathData="{mark_path()}">
        <aapt:attr name="android:fillColor">
            <gradient
                android:type="linear"
                android:startX="{GRADIENT_START[0]}"
                android:startY="{GRADIENT_START[1]}"
                android:endX="{GRADIENT_END[0]}"
                android:endY="{GRADIENT_END[1]}">
{stops}
            </gradient>
        </aapt:attr>
    </path>
</vector>
"""
    background = f"""{VECTOR_HEADER}<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path android:pathData="M0,0H108V108H0Z">
        <aapt:attr name="android:fillColor">
            <gradient
                android:type="radial"
                android:centerX="{GLOW_CENTER[0]}"
                android:centerY="{GLOW_CENTER[1]}"
                android:gradientRadius="{GLOW_RADIUS}">
                <item android:offset="0" android:color="{hex_color(GLOW)}" />
                <item android:offset="1" android:color="{hex_color(INK)}" />
            </gradient>
        </aapt:attr>
    </path>
</vector>
"""
    monochrome = f"""{VECTOR_HEADER}<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path android:fillColor="#FFFFFFFF" android:pathData="{mark_path()}" />
</vector>
"""
    adaptive = f"""{VECTOR_HEADER}<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />
</adaptive-icon>
"""
    drawable = RES / "drawable"
    drawable.mkdir(parents=True, exist_ok=True)
    (drawable / "ic_launcher_foreground.xml").write_text(foreground)
    (drawable / "ic_launcher_background.xml").write_text(background)
    (drawable / "ic_launcher_monochrome.xml").write_text(monochrome)
    anydpi = RES / "mipmap-anydpi-v26"
    anydpi.mkdir(parents=True, exist_ok=True)
    (anydpi / "ic_launcher.xml").write_text(adaptive)
    (anydpi / "ic_launcher_round.xml").write_text(adaptive)


def lerp(a: tuple[int, int, int], b: tuple[int, int, int], t: float) -> tuple[int, int, int]:
    return tuple(round(x + (y - x) * t) for x, y in zip(a, b, strict=True))


def gradient_color(t: float) -> tuple[int, int, int]:
    t = min(max(t, 0.0), 1.0)
    for (o1, c1), (o2, c2) in zip(GRADIENT_STOPS, GRADIENT_STOPS[1:], strict=False):
        if t <= o2:
            return lerp(c1, c2, (t - o1) / (o2 - o1))
    return GRADIENT_STOPS[-1][1]


def render(size: int, shape: str | None) -> Image.Image:
    """Draw the icon at ``size`` px. ``shape`` is "square", "circle" or None (full bleed)."""
    lo, hi = VISIBLE
    margin = size / 24 if shape else 0  # legacy icons keep 2 dp of air on a 48 dp tile
    scale = (size - 2 * margin) / (hi - lo)

    def to_canvas(x: float, y: float) -> tuple[float, float]:
        return margin + (x - lo) * scale, margin + (y - lo) * scale

    def to_viewport(px: float, py: float) -> tuple[float, float]:
        return lo + (px - margin) / scale, lo + (py - margin) / scale

    background = Image.new("RGB", (size, size))
    foreground = Image.new("RGB", (size, size))
    gx, gy = GRADIENT_END[0] - GRADIENT_START[0], GRADIENT_END[1] - GRADIENT_START[1]
    glen2 = gx * gx + gy * gy
    bg_pixels, fg_pixels = [], []
    for py in range(size):
        for px in range(size):
            x, y = to_viewport(px + 0.5, py + 0.5)
            dist = math.hypot(x - GLOW_CENTER[0], y - GLOW_CENTER[1]) / GLOW_RADIUS
            bg_pixels.append(lerp(GLOW, INK, min(dist, 1.0)))
            t = ((x - GRADIENT_START[0]) * gx + (y - GRADIENT_START[1]) * gy) / glen2
            fg_pixels.append(gradient_color(t))
    background.putdata(bg_pixels)
    foreground.putdata(fg_pixels)

    big = size * SUPERSAMPLE

    def mask(draw_fn) -> Image.Image:
        image = Image.new("L", (big, big), 0)
        draw_fn(ImageDraw.Draw(image), lambda x, y: tuple(v * SUPERSAMPLE for v in to_canvas(x, y)))
        return image.reduce(SUPERSAMPLE)

    def draw_mark(draw: ImageDraw.ImageDraw, at) -> None:
        for l, t, r, b in RECTS:
            draw.rectangle([at(l, t), at(r, b)], fill=255)
        draw.polygon([at(x, y) for x, y in sparkle_points()], fill=255)

    tile = background.copy()
    tile.paste(foreground, mask=mask(draw_mark))
    out = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    if shape is None:
        out.paste(tile)
        return out

    def draw_shape(draw: ImageDraw.ImageDraw, _at) -> None:
        box = [margin * SUPERSAMPLE, margin * SUPERSAMPLE, big - margin * SUPERSAMPLE, big - margin * SUPERSAMPLE]
        if shape == "circle":
            draw.ellipse(box, fill=255)
        else:
            draw.rounded_rectangle(box, radius=(big - 2 * margin * SUPERSAMPLE) * 0.22, fill=255)

    out.paste(tile, mask=mask(draw_shape))
    return out


def write_pngs() -> None:
    for density, size in LEGACY_SIZES.items():
        folder = RES / f"mipmap-{density}"
        folder.mkdir(parents=True, exist_ok=True)
        render(size, "square").save(folder / "ic_launcher.png", optimize=True)
        render(size, "circle").save(folder / "ic_launcher_round.png", optimize=True)
    branding = ROOT / "branding"
    branding.mkdir(exist_ok=True)
    render(512, None).convert("RGB").save(branding / "play_store_icon_512.png", optimize=True)


if __name__ == "__main__":
    write_vectors()
    write_pngs()
    print("Icons written to", RES.relative_to(ROOT), "and branding/")
