"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-24 17:36:46.743378
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_users",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("totp_secret_ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_users")),
        sa.UniqueConstraint("username", name=op.f("uq_admin_users_username")),
    )
    op.create_table(
        "app_settings",
        sa.Column("id", sa.Integer(), server_default="1", nullable=False),
        sa.Column("company_name", sa.String(length=100), server_default="Future Fashion", nullable=False),
        sa.Column("company_legal_name", sa.String(length=200), nullable=True),
        sa.Column("company_address", sa.Text(), nullable=True),
        sa.Column("support_email", sa.String(length=200), nullable=True),
        sa.Column("support_url", sa.Text(), nullable=True),
        sa.Column("terms_url", sa.Text(), nullable=True),
        sa.Column("privacy_url", sa.Text(), nullable=True),
        sa.Column("min_app_version", sa.String(length=20), server_default="1.0.0", nullable=False),
        sa.Column("apk_download_url", sa.Text(), nullable=True),
        sa.Column("maintenance_active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("maintenance_message", sa.String(length=300), nullable=True),
        sa.Column("maintenance_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("announcement_text", sa.String(length=300), nullable=True),
        sa.Column("announcement_tone", sa.Text(), nullable=True),
        sa.Column("ads_banner_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("ads_interstitial_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("ads_rewarded_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("ads_min_interstitial_interval_seconds", sa.Integer(), server_default="300", nullable=False),
        sa.Column("accept_pending_join_requests", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("verification_session_minutes", sa.Integer(), server_default="30", nullable=False),
        sa.Column("max_contact_mismatches", sa.Integer(), server_default="3", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "announcement_tone IS NULL OR announcement_tone IN ('info', 'success', 'warning')",
            name=op.f("ck_app_settings_announcement_tone"),
        ),
        sa.CheckConstraint("ads_min_interstitial_interval_seconds >= 60", name=op.f("ck_app_settings_interstitial_interval")),
        sa.CheckConstraint("id = 1", name=op.f("ck_app_settings_single_row")),
        sa.CheckConstraint("max_contact_mismatches BETWEEN 1 AND 10", name=op.f("ck_app_settings_mismatch_limit")),
        sa.CheckConstraint("verification_session_minutes BETWEEN 5 AND 1440", name=op.f("ck_app_settings_session_minutes")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_settings")),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("actor", sa.String(length=80), nullable=False),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("target", sa.String(length=80), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index("ix_audit_log_recent", "audit_log", [sa.literal_column("id DESC")], unique=False)
    op.create_index("ix_audit_log_target", "audit_log", ["target"], unique=False)
    op.create_table(
        "campaigns",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("brand_reveal_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("launch_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payout_opens_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("brand_name", sa.String(length=100), nullable=True),
        sa.Column("level_1_reward_paise", sa.BigInteger(), nullable=False),
        sa.Column("min_withdrawal_paise", sa.BigInteger(), nullable=False),
        sa.Column("capacity", sa.BigInteger(), nullable=False),
        sa.Column("signups_open", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("paused", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("show_promo_allocation", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_current", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("capacity > 0", name=op.f("ck_campaigns_capacity_positive")),
        sa.CheckConstraint("level_1_reward_paise > 0", name=op.f("ck_campaigns_reward_positive")),
        sa.CheckConstraint("min_withdrawal_paise > 0", name=op.f("ck_campaigns_min_withdrawal_positive")),
        sa.CheckConstraint("starts_at < ends_at", name=op.f("ck_campaigns_dates_ordered")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaigns")),
    )
    op.create_index("uq_campaigns_current", "campaigns", ["is_current"], unique=True, postgresql_where=sa.text("is_current"))
    op.create_table(
        "idempotency_keys",
        sa.Column("scope", sa.String(length=80), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("request_hash", sa.LargeBinary(), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_body", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("scope", "key", name="pk_idempotency_keys"),
    )
    op.create_index("ix_idempotency_keys_expiry", "idempotency_keys", ["expires_at"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("dedupe_key", sa.String(length=150), nullable=True),
        sa.Column("status", sa.Text(), server_default="QUEUED", nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default="5", nullable=False),
        sa.Column("run_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("status IN ('QUEUED', 'RUNNING', 'DONE', 'FAILED')", name=op.f("ck_jobs_status")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("dedupe_key", name=op.f("uq_jobs_dedupe_key")),
    )
    op.create_index("ix_jobs_ready", "jobs", ["run_at"], unique=False, postgresql_where=sa.text("status = 'QUEUED'"))
    op.create_index("ix_jobs_running", "jobs", ["locked_until"], unique=False, postgresql_where=sa.text("status = 'RUNNING'"))
    op.create_table(
        "ledger_transactions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.String(length=10), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("reference_type", sa.Text(), nullable=True),
        sa.Column("reference_id", sa.BigInteger(), nullable=True),
        sa.Column("created_by", sa.Text(), nullable=False),
        sa.Column("memo", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "kind IN ('FUNDING', 'REFERRAL_REWARD', 'REWARDS_UNLOCK', 'WITHDRAWAL_HOLD', 'WITHDRAWAL_PAID', 'WITHDRAWAL_RETURNED', 'ADJUSTMENT')",
            name=op.f("ck_ledger_transactions_kind"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ledger_transactions")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_ledger_transactions_idempotency_key")),
        sa.UniqueConstraint("public_id", name=op.f("uq_ledger_transactions_public_id")),
    )
    op.create_table(
        "membership_counter",
        sa.Column("id", sa.Integer(), server_default="1", nullable=False),
        sa.Column("verified_count", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("id = 1", name=op.f("ck_membership_counter_single_row")),
        sa.CheckConstraint("verified_count >= 0", name=op.f("ck_membership_counter_non_negative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_membership_counter")),
    )
    op.create_table(
        "payout_batches",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_by", sa.Text(), nullable=False),
        sa.Column("request_count", sa.BigInteger(), nullable=False),
        sa.Column("total_paise", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payout_batches")),
    )
    op.create_table(
        "required_channels",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("invite_link", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_required_channels")),
        sa.UniqueConstraint("chat_id", name=op.f("uq_required_channels_chat_id")),
    )
    op.create_table(
        "telegram_bots",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ref", sa.String(length=32), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("telegram_bot_id", sa.BigInteger(), nullable=False),
        sa.Column("token_ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("webhook_secret_hash", sa.LargeBinary(), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("health", sa.Text(), server_default="HEALTHY", nullable=False),
        sa.Column("rate_limited_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), server_default="0", nullable=False),
        sa.Column("weight", sa.Integer(), server_default="1", nullable=False),
        sa.Column("last_ok_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("health IN ('HEALTHY', 'RATE_LIMITED', 'FAILING')", name=op.f("ck_telegram_bots_health")),
        sa.CheckConstraint("role IN ('VERIFIER', 'WATCHER')", name=op.f("ck_telegram_bots_role")),
        sa.CheckConstraint("weight BETWEEN 1 AND 100", name=op.f("ck_telegram_bots_weight_range")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_telegram_bots")),
        sa.UniqueConstraint("ref", name=op.f("uq_telegram_bots_ref")),
        sa.UniqueConstraint("telegram_bot_id", name=op.f("uq_telegram_bots_telegram_bot_id")),
        sa.UniqueConstraint("username", name=op.f("uq_telegram_bots_username")),
    )
    op.create_table(
        "telegram_join_requests",
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("telegram_user_id", "chat_id", name="pk_telegram_join_requests"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.String(length=8), nullable=False),
        sa.Column("phone", sa.String(length=10), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="PENDING_VERIFICATION", nullable=False),
        sa.Column("referrer_id", sa.BigInteger(), nullable=True),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=True),
        sa.Column("pending_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("suspended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("phone ~ '^[6-9][0-9]{9}$'", name=op.f("ck_users_phone_format")),
        sa.CheckConstraint("status IN ('PENDING_VERIFICATION', 'ACTIVE', 'SUSPENDED')", name=op.f("ck_users_status")),
        sa.CheckConstraint("referrer_id IS NULL OR referrer_id <> id", name=op.f("ck_users_not_self_referred")),
        sa.ForeignKeyConstraint(["referrer_id"], ["users.id"], name=op.f("fk_users_referrer_id_users"), ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("phone", name=op.f("uq_users_phone")),
        sa.UniqueConstraint("public_id", name=op.f("uq_users_public_id")),
        sa.UniqueConstraint("telegram_user_id", name=op.f("uq_users_telegram_user_id")),
    )
    op.create_index(
        "ix_users_pending_expiry",
        "users",
        ["pending_expires_at"],
        unique=False,
        postgresql_where=sa.text("status = 'PENDING_VERIFICATION'"),
    )
    op.create_index(
        "ix_users_referrer_recent",
        "users",
        ["referrer_id", sa.literal_column("created_at DESC"), sa.literal_column("id DESC")],
        unique=False,
    )
    op.create_table(
        "admin_sessions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("admin_id", sa.BigInteger(), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(), nullable=False),
        sa.Column("csrf_token", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["admin_id"], ["admin_users.id"], name=op.f("fk_admin_sessions_admin_id_admin_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_admin_sessions_token_hash")),
    )
    op.create_table(
        "auth_sessions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("access_token_hash", sa.LargeBinary(), nullable=False),
        sa.Column("access_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("refresh_token_hash", sa.LargeBinary(), nullable=False),
        sa.Column("refresh_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rotated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_auth_sessions_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_sessions")),
        sa.UniqueConstraint("access_token_hash", name=op.f("uq_auth_sessions_access_token_hash")),
        sa.UniqueConstraint("refresh_token_hash", name=op.f("uq_auth_sessions_refresh_token_hash")),
    )
    op.create_index("ix_auth_sessions_family", "auth_sessions", ["family_id"], unique=False)
    op.create_index("ix_auth_sessions_user", "auth_sessions", ["user_id"], unique=False)
    op.create_table(
        "bank_accounts",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("account_holder_name", sa.String(length=100), nullable=False),
        sa.Column("account_number_ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("account_number_last4", sa.String(length=4), nullable=False),
        sa.Column("account_number_fingerprint", sa.LargeBinary(), nullable=False),
        sa.Column("ifsc", sa.String(length=11), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("account_number_last4 ~ '^[0-9]{4}$'", name=op.f("ck_bank_accounts_last4_format")),
        sa.CheckConstraint("ifsc ~ '^[A-Z]{4}0[A-Z0-9]{6}$'", name=op.f("ck_bank_accounts_ifsc_format")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_bank_accounts_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_bank_accounts")),
    )
    op.create_index("ix_bank_accounts_fingerprint", "bank_accounts", ["account_number_fingerprint"], unique=False)
    op.create_table(
        "ledger_accounts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("balance_paise", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "(kind IN ('USER_PENDING', 'USER_AVAILABLE')) = (user_id IS NOT NULL)",
            name=op.f("ck_ledger_accounts_user_accounts_have_owner"),
        ),
        sa.CheckConstraint("kind = 'COMPANY_FUNDING' OR balance_paise >= 0", name=op.f("ck_ledger_accounts_no_negative_balance")),
        sa.CheckConstraint(
            "kind IN ('COMPANY_FUNDING', 'PROMO_POOL', 'USER_PENDING', 'USER_AVAILABLE', 'WITHDRAWAL_CLEARING', 'PAYOUT_SETTLED')",
            name=op.f("ck_ledger_accounts_kind"),
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_ledger_accounts_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ledger_accounts")),
    )
    op.create_index(
        "uq_ledger_accounts_system_kind", "ledger_accounts", ["kind"], unique=True, postgresql_where=sa.text("user_id IS NULL")
    )
    op.create_index(
        "uq_ledger_accounts_user_kind",
        "ledger_accounts",
        ["kind", "user_id"],
        unique=True,
        postgresql_where=sa.text("user_id IS NOT NULL"),
    )
    op.create_table(
        "referral_edges",
        sa.Column("ancestor_id", sa.BigInteger(), nullable=False),
        sa.Column("descendant_id", sa.BigInteger(), nullable=False),
        sa.Column("level", sa.SmallInteger(), nullable=False),
        sa.Column("status", sa.Text(), server_default="PENDING", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("qualified_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("status IN ('PENDING', 'QUALIFIED')", name=op.f("ck_referral_edges_status")),
        sa.CheckConstraint("ancestor_id <> descendant_id", name=op.f("ck_referral_edges_no_self_edge")),
        sa.CheckConstraint("level BETWEEN 1 AND 4", name=op.f("ck_referral_edges_level_range")),
        sa.ForeignKeyConstraint(
            ["ancestor_id"], ["users.id"], name=op.f("fk_referral_edges_ancestor_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["descendant_id"], ["users.id"], name=op.f("fk_referral_edges_descendant_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("descendant_id", "level", name="pk_referral_edges"),
        sa.UniqueConstraint("ancestor_id", "descendant_id", name=op.f("uq_referral_edges_ancestor_id_descendant_id")),
    )
    op.create_index(
        "ix_referral_edges_counting",
        "referral_edges",
        ["ancestor_id", "level"],
        unique=False,
        postgresql_where=sa.text("status = 'QUALIFIED'"),
    )
    op.create_table(
        "referral_rewards",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("beneficiary_id", sa.BigInteger(), nullable=False),
        sa.Column("source_user_id", sa.BigInteger(), nullable=False),
        sa.Column("level", sa.SmallInteger(), nullable=False),
        sa.Column("amount_paise", sa.BigInteger(), nullable=False),
        sa.Column("campaign_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.Text(), server_default="CREDITED", nullable=False),
        sa.Column("ledger_transaction_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("status IN ('CREDITED', 'REVERSED')", name=op.f("ck_referral_rewards_status")),
        sa.CheckConstraint("amount_paise > 0", name=op.f("ck_referral_rewards_amount_positive")),
        sa.CheckConstraint("beneficiary_id <> source_user_id", name=op.f("ck_referral_rewards_no_self_reward")),
        sa.CheckConstraint("level = 1", name=op.f("ck_referral_rewards_only_level_one_pays")),
        sa.ForeignKeyConstraint(["beneficiary_id"], ["users.id"], name=op.f("fk_referral_rewards_beneficiary_id_users")),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], name=op.f("fk_referral_rewards_campaign_id_campaigns")),
        sa.ForeignKeyConstraint(
            ["ledger_transaction_id"],
            ["ledger_transactions.id"],
            name=op.f("fk_referral_rewards_ledger_transaction_id_ledger_transactions"),
        ),
        sa.ForeignKeyConstraint(["source_user_id"], ["users.id"], name=op.f("fk_referral_rewards_source_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_referral_rewards")),
        sa.UniqueConstraint("ledger_transaction_id", name=op.f("uq_referral_rewards_ledger_transaction_id")),
        sa.UniqueConstraint("source_user_id", "level", name=op.f("uq_referral_rewards_source_user_id_level")),
    )
    op.create_index("ix_referral_rewards_beneficiary", "referral_rewards", ["beneficiary_id", "created_at"], unique=False)
    op.create_table(
        "referral_snapshots",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("level_1_count", sa.Integer(), nullable=False),
        sa.Column("level_2_count", sa.Integer(), nullable=False),
        sa.Column("level_3_count", sa.Integer(), nullable=False),
        sa.Column("level_4_count", sa.Integer(), nullable=False),
        sa.Column("level_1_income_paise", sa.BigInteger(), nullable=False),
        sa.Column("level_2_income_paise", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("level_3_income_paise", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("level_4_income_paise", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "level_1_count >= 0 AND level_2_count >= 0 AND level_3_count >= 0 AND level_4_count >= 0",
            name=op.f("ck_referral_snapshots_counts_non_negative"),
        ),
        sa.CheckConstraint("level_1_income_paise >= 0", name=op.f("ck_referral_snapshots_level_1_income_non_negative")),
        sa.CheckConstraint("level_2_income_paise = 0", name=op.f("ck_referral_snapshots_level_2_unpaid")),
        sa.CheckConstraint("level_3_income_paise = 0", name=op.f("ck_referral_snapshots_level_3_unpaid")),
        sa.CheckConstraint("level_4_income_paise = 0", name=op.f("ck_referral_snapshots_level_4_unpaid")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_referral_snapshots_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_referral_snapshots")),
    )
    op.create_table(
        "risk_flags",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.String(length=80), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_risk_flags_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_flags")),
    )
    op.create_index(
        "ix_risk_flags_open", "risk_flags", ["created_at"], unique=False, postgresql_where=sa.text("resolved_at IS NULL")
    )
    op.create_index("ix_risk_flags_user", "risk_flags", ["user_id"], unique=False)
    op.create_table(
        "telegram_verification_sessions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("bot_id", sa.BigInteger(), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(), nullable=True),
        sa.Column("status", sa.Text(), server_default="OPEN", nullable=False),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=True),
        sa.Column("channels_confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("mismatch_count", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("issue", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('OPEN', 'IN_PROGRESS', 'COMPLETED', 'EXPIRED', 'FAILED', 'SUPERSEDED')",
            name=op.f("ck_telegram_verification_sessions_status"),
        ),
        sa.ForeignKeyConstraint(
            ["bot_id"], ["telegram_bots.id"], name=op.f("fk_telegram_verification_sessions_bot_id_telegram_bots")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_telegram_verification_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_telegram_verification_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_telegram_verification_sessions_token_hash")),
    )
    op.create_index(
        "ix_telegram_verification_sessions_tg_user",
        "telegram_verification_sessions",
        ["telegram_user_id"],
        unique=False,
        postgresql_where=sa.text("status IN ('OPEN', 'IN_PROGRESS')"),
    )
    op.create_index(
        "ix_telegram_verification_sessions_user_recent",
        "telegram_verification_sessions",
        ["user_id", sa.literal_column("id DESC")],
        unique=False,
    )
    op.create_index(
        "uq_telegram_verification_sessions_one_open",
        "telegram_verification_sessions",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('OPEN', 'IN_PROGRESS')"),
    )
    op.create_table(
        "withdrawal_requests",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.String(length=10), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("amount_paise", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.Text(), server_default="REQUESTED", nullable=False),
        sa.Column("account_holder_name", sa.String(length=100), nullable=False),
        sa.Column("account_number_ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("account_number_last4", sa.String(length=4), nullable=False),
        sa.Column("ifsc", sa.String(length=11), nullable=False),
        sa.Column("hold_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("settle_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("batch_id", sa.BigInteger(), nullable=True),
        sa.Column("bank_reference", sa.String(length=64), nullable=True),
        sa.Column("failure_reason", sa.String(length=200), nullable=True),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processing_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("status IN ('REQUESTED', 'PROCESSING', 'PAID', 'FAILED')", name=op.f("ck_withdrawal_requests_status")),
        sa.CheckConstraint("amount_paise > 0", name=op.f("ck_withdrawal_requests_amount_positive")),
        sa.ForeignKeyConstraint(["batch_id"], ["payout_batches.id"], name=op.f("fk_withdrawal_requests_batch_id_payout_batches")),
        sa.ForeignKeyConstraint(
            ["hold_transaction_id"],
            ["ledger_transactions.id"],
            name=op.f("fk_withdrawal_requests_hold_transaction_id_ledger_transactions"),
        ),
        sa.ForeignKeyConstraint(
            ["settle_transaction_id"],
            ["ledger_transactions.id"],
            name=op.f("fk_withdrawal_requests_settle_transaction_id_ledger_transactions"),
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_withdrawal_requests_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_withdrawal_requests")),
        sa.UniqueConstraint("public_id", name=op.f("uq_withdrawal_requests_public_id")),
    )
    op.create_index("ix_withdrawal_requests_status", "withdrawal_requests", ["status", "requested_at"], unique=False)
    op.create_index(
        "ix_withdrawal_requests_user_recent",
        "withdrawal_requests",
        ["user_id", sa.literal_column("requested_at DESC")],
        unique=False,
    )
    op.create_index(
        "uq_withdrawal_requests_one_active",
        "withdrawal_requests",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('REQUESTED', 'PROCESSING')"),
    )
    op.create_table(
        "ledger_entries",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("transaction_id", sa.BigInteger(), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("amount_paise", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("amount_paise <> 0", name=op.f("ck_ledger_entries_amount_non_zero")),
        sa.ForeignKeyConstraint(
            ["account_id"], ["ledger_accounts.id"], name=op.f("fk_ledger_entries_account_id_ledger_accounts")
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"], ["ledger_transactions.id"], name=op.f("fk_ledger_entries_transaction_id_ledger_transactions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ledger_entries")),
    )
    op.create_index(
        "ix_ledger_entries_account_recent", "ledger_entries", ["account_id", sa.literal_column("id DESC")], unique=False
    )
    op.create_index("ix_ledger_entries_transaction", "ledger_entries", ["transaction_id"], unique=False)
    op.create_table(
        "telegram_verifications",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("session_id", sa.BigInteger(), nullable=False),
        sa.Column("bot_id", sa.BigInteger(), nullable=False),
        sa.Column("channel_states", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["bot_id"], ["telegram_bots.id"], name=op.f("fk_telegram_verifications_bot_id_telegram_bots")),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["telegram_verification_sessions.id"],
            name=op.f("fk_telegram_verifications_session_id_telegram_verification_sessions"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_telegram_verifications_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_telegram_verifications")),
        sa.UniqueConstraint("telegram_user_id", name=op.f("uq_telegram_verifications_telegram_user_id")),
    )

    # --- Rules the database enforces on its own -------------------------------

    # Every ledger transaction must balance: its entries sum to zero. Checked
    # at commit so a transaction can insert its entries one by one.
    op.execute("""
        CREATE FUNCTION ledger_check_balanced() RETURNS trigger AS $$
        DECLARE total bigint;
        BEGIN
            SELECT COALESCE(SUM(amount_paise), 0) INTO total
              FROM ledger_entries WHERE transaction_id = NEW.transaction_id;
            IF total <> 0 THEN
                RAISE EXCEPTION 'ledger transaction % does not balance (sum %)', NEW.transaction_id, total
                    USING ERRCODE = 'check_violation';
            END IF;
            RETURN NULL;
        END $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE CONSTRAINT TRIGGER ledger_entries_balanced
        AFTER INSERT ON ledger_entries
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW EXECUTE FUNCTION ledger_check_balanced();
    """)

    # History is never rewritten: ledger and audit rows can't be changed or deleted.
    op.execute("""
        CREATE FUNCTION reject_change() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION '% is append-only', TG_TABLE_NAME USING ERRCODE = 'insufficient_privilege';
        END $$ LANGUAGE plpgsql;
    """)
    for table in ("ledger_entries", "ledger_transactions", "audit_log"):
        op.execute(f"""
            CREATE TRIGGER {table}_append_only
            BEFORE UPDATE OR DELETE ON {table}
            FOR EACH ROW EXECUTE FUNCTION reject_change();
        """)

    # --- Initial rows ------------------------------------------------------------
    op.execute("INSERT INTO app_settings (id) VALUES (1)")
    op.execute("INSERT INTO membership_counter (id, verified_count) VALUES (1, 0)")
    op.execute("""
        INSERT INTO ledger_accounts (kind) VALUES
            ('COMPANY_FUNDING'), ('PROMO_POOL'), ('WITHDRAWAL_CLEARING'), ('PAYOUT_SETTLED')
    """)
    # The campaign agreed on 24 September 2026. Every value is editable in the
    # admin panel. Times are IST: reveal 21 Dec, launch and payout 31 Dec at
    # 00:00, end 31 Dec 23:59:59. ₹200 = 20000 paise; capacity 5 crore.
    op.execute("""
        INSERT INTO campaigns (name, starts_at, ends_at, brand_reveal_at, launch_at, payout_opens_at,
                               level_1_reward_paise, min_withdrawal_paise, capacity)
        VALUES ('Future Fashion launch', now(),
                '2026-12-31 23:59:59+05:30', '2026-12-21 00:00:00+05:30',
                '2026-12-31 00:00:00+05:30', '2026-12-31 00:00:00+05:30',
                20000, 20000, 50000000)
    """)
    # ### end Alembic commands ###


def downgrade() -> None:

    op.execute("DROP TRIGGER IF EXISTS ledger_entries_balanced ON ledger_entries")
    for table in ("ledger_entries", "ledger_transactions", "audit_log"):
        op.execute(f"DROP TRIGGER IF EXISTS {table}_append_only ON {table}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("telegram_verifications")
    op.drop_index("ix_ledger_entries_transaction", table_name="ledger_entries")
    op.drop_index("ix_ledger_entries_account_recent", table_name="ledger_entries")
    op.drop_table("ledger_entries")
    op.drop_index(
        "uq_withdrawal_requests_one_active",
        table_name="withdrawal_requests",
        postgresql_where=sa.text("status IN ('REQUESTED', 'PROCESSING')"),
    )
    op.drop_index("ix_withdrawal_requests_user_recent", table_name="withdrawal_requests")
    op.drop_index("ix_withdrawal_requests_status", table_name="withdrawal_requests")
    op.drop_table("withdrawal_requests")
    op.drop_index(
        "uq_telegram_verification_sessions_one_open",
        table_name="telegram_verification_sessions",
        postgresql_where=sa.text("status IN ('OPEN', 'IN_PROGRESS')"),
    )
    op.drop_index("ix_telegram_verification_sessions_user_recent", table_name="telegram_verification_sessions")
    op.drop_index(
        "ix_telegram_verification_sessions_tg_user",
        table_name="telegram_verification_sessions",
        postgresql_where=sa.text("status IN ('OPEN', 'IN_PROGRESS')"),
    )
    op.drop_table("telegram_verification_sessions")
    op.drop_index("ix_risk_flags_user", table_name="risk_flags")
    op.drop_index("ix_risk_flags_open", table_name="risk_flags", postgresql_where=sa.text("resolved_at IS NULL"))
    op.drop_table("risk_flags")
    op.drop_table("referral_snapshots")
    op.drop_index("ix_referral_rewards_beneficiary", table_name="referral_rewards")
    op.drop_table("referral_rewards")
    op.drop_index("ix_referral_edges_counting", table_name="referral_edges", postgresql_where=sa.text("status = 'QUALIFIED'"))
    op.drop_table("referral_edges")
    op.drop_index("uq_ledger_accounts_user_kind", table_name="ledger_accounts", postgresql_where=sa.text("user_id IS NOT NULL"))
    op.drop_index("uq_ledger_accounts_system_kind", table_name="ledger_accounts", postgresql_where=sa.text("user_id IS NULL"))
    op.drop_table("ledger_accounts")
    op.drop_index("ix_bank_accounts_fingerprint", table_name="bank_accounts")
    op.drop_table("bank_accounts")
    op.drop_index("ix_auth_sessions_user", table_name="auth_sessions")
    op.drop_index("ix_auth_sessions_family", table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_table("admin_sessions")
    op.drop_index("ix_users_referrer_recent", table_name="users")
    op.drop_index("ix_users_pending_expiry", table_name="users", postgresql_where=sa.text("status = 'PENDING_VERIFICATION'"))
    op.drop_table("users")
    op.drop_table("telegram_join_requests")
    op.drop_table("telegram_bots")
    op.drop_table("required_channels")
    op.drop_table("payout_batches")
    op.drop_table("membership_counter")
    op.drop_table("ledger_transactions")
    op.drop_index("ix_jobs_running", table_name="jobs", postgresql_where=sa.text("status = 'RUNNING'"))
    op.drop_index("ix_jobs_ready", table_name="jobs", postgresql_where=sa.text("status = 'QUEUED'"))
    op.drop_table("jobs")
    op.drop_index("ix_idempotency_keys_expiry", table_name="idempotency_keys")
    op.drop_table("idempotency_keys")
    op.drop_index("uq_campaigns_current", table_name="campaigns", postgresql_where=sa.text("is_current"))
    op.drop_table("campaigns")
    op.drop_index("ix_audit_log_target", table_name="audit_log")
    op.drop_index("ix_audit_log_recent", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_table("app_settings")
    op.drop_table("admin_users")
    # ### end Alembic commands ###
    op.execute("DROP FUNCTION IF EXISTS ledger_check_balanced()")
    op.execute("DROP FUNCTION IF EXISTS reject_change()")
